### ISSUE TITLE
Does not work with multiple file contexts

### ISSUE THREAD

**Issue by ryan-dyer-sp** [witalisoft/mkubectx#1]
KUBECONFIG is a list, not just a single file.  We use oidc for authentication with our clusters, so out KUBECONFIG="cluster1,cluster2,oidc-auth"  Where the clusterX files defines the server and context definitions and oidc-auth defines the users section of a kubeconfig.  It appears that the kubeconfig.go doesnt really handle this scenario as getKubeConfigContexts only appears to support a single file.

Just a question/thought, why not use kubectl for getting the contexts currently available instead of trying to parse it from the files themselves?

**Comment by witalisoft** [comment]
Thanks for suggestion

I've added commit with support multiple files in KUBECONFIG env (https://github.com/witalisoft/mkubectx/commit/90b29a02a9f929b90233caa8608179f2dd0bd22b)

> Just a question/thought, why not use kubectl for getting the contexts currently available instead of trying to parse it from the files themselves?

mkubectx is working in parallel mode, so using kubectl it could led to race conditions
